### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by BestCap** [kartikk221/spotify-true-shuffle#14]
Hello.  I noticed the site no longer working today.  I tried to use it and it gave me this message

"Failed to disable playback shuffle in Spotify player."

I tried turning shuffle off on Spotify, pausing/playing the music, nothing seemed to work.  Really enjoyed using this site as Spotify shuffle sucks, so would love to get it back working

**Comment by okawaffles** [comment]
gonna fork it and see if i can fix it. i'll keep you updated

**Comment by okawaffles** [comment]
fixed it in #15 
if the maintainer is inactive I'll apply for an API extension and leave a URL here.

if you'd like, shoot me a DM on Discord @okawaffles and I'll help you use mine. (spotify developer application is unapproved as of now, so I need to manually add you as a tester)

**Comment by ritoradio** [comment]
I'm having the same issue, it still doesnt seemed to be fixed. Also most of the time I use it, around 60% it would "Failed to disable playback shuffle in Spotify player." and i'd need to restart both chrome on my phone and spotify, and then it would work after doing that a few times.

**Comment by ritoradio** [comment]
I'm having the same issue, as in it now always gives me that error instead of 60% of the time.

**Comment by zaida037** [comment]
Same here, it doesn't work anymore.

**Comment by kartikk221** [comment]
Hey "Failed to disable playback shuffle in Spotify player." this usually occurs because you don't have Spotify Premium which spotify requires for us to directly playback the shuffled songs.

But there should be fallback logic which creates a temporary playlist with the shuffled music.

Could you provide some console logs when this occurs?

**Comment by okawaffles** [comment]
It's simply an error about an incorrect http code. The shuffle is expecting the http code 204 but Spotify has been returning 200 instead.

I will provide exact logs when I am on my PC (replying from mobile atm)

**Comment by kartikk221** [comment]
> It's simply an error about an incorrect http code. The shuffle is expecting the http code 204 but Spotify has been returning 200 instead.
> 
> I will provide exact logs when I am on my PC (replying from mobile atm)

Oh I see, I just merged your PR. Did that fix the issue?

**Comment by okawaffles** [comment]
Yup, your webpage is working again.
